import scrapy
from datetime import datetime, timedelta
from urllib.parse import urlparse, parse_qs

BASE_URL = "https://www.imankatolik.or.id/kalender.php?"
# converts month number to ID abbrev for months, index 0 is empty
NUM_TO_MONTH_ID = ["", "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"] 

# gives all datetime objects of sundays between two given dates. Generated by ChatGPT
def sundays_between(start_date, end_date):
    # Ensure datetime objects
    if isinstance(start_date, str):
        start_date = datetime.strptime(start_date, "%Y-%m-%d")
    if isinstance(end_date, str):
        end_date = datetime.strptime(end_date, "%Y-%m-%d")
    
    # Move to the first Sunday on or after the start date
    days_until_sunday = (6 - start_date.weekday()) % 7
    first_sunday = start_date + timedelta(days=days_until_sunday)

    # Generate all Sundays up to and including the end date
    sundays = []
    current = first_sunday
    while current <= end_date:
        sundays.append(current)
        current += timedelta(weeks=1)

    return sundays

class CalendarSpider(scrapy.Spider):
    name = "calendar"
    

    async def start(self):
        urls = []
        year = 2025
        months = [m for m in range(6,13)]

        for month in months:
            urls.append(f"{BASE_URL}b={month}&t={year}")

        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        month_dates = []
        res = dict()
        dates = sundays_between("2025-06-01", "2026-01-01")
        
        for d in dates:
            parsed_url = urlparse(response.url)
            query_params = parse_qs(parsed_url.query)
            url_month = int(query_params.get("b", [None])[0])

            if d.month == url_month:
                month_dates.append(d)
        
        for d in month_dates:

            day = d.day
            month = NUM_TO_MONTH_ID[d.month]

            # this gets mass title in indo
            mass_title = response.xpath(f'//a[@href="/kalender/{day}{month}.html"]/div[@class="k_perayaan"]//text()').getall()
            mass_title = "".join(mass_title).replace("\r", "").replace("\n", "").lower()

            res[d.strftime("%Y-%m-%d")] = mass_title

        yield res